In [1]:
import openferro as of
from openferro.interaction import *
from openferro.simulation import *
from openferro.engine import *
from openferro.ewald import dipole_dipole_ewald
from matplotlib import pyplot as plt
import json


In [17]:
L =12
config = json.load(open('../model_configs/BaTiO3.json'))
latt_vecs = jnp.eye(3) * config['lattice']['a1']
latt = of.BravaisLattice3D(L, L, L, latt_vecs[0], latt_vecs[1], latt_vecs[2])
bto = of.System(latt, pbc=True)
## define fields
dipole_field = bto.add_field(name="dipole", ftype="Rn", dim=3, value=0.1, mass = 40)
lstrain_field = bto.add_field(name="lstrain", ftype="local_strain", value=0.0, mass = 10)
gstrain_field = bto.add_field(name="gstrain", ftype="global_strain", value=jnp.zeros(6), mass = 10000)

## define Hamiltonian
bto.add_self_interaction('self_onsite', field_name="dipole", energy_engine=self_energy_onsite_isotropic, parameters=config["onsite"], enable_jit=True)
bto.add_self_interaction('short_range_1', field_name="dipole", energy_engine=short_range_1stnn_isotropic, parameters=config["short_range"], enable_jit=True)
bto.add_self_interaction('short_range_2', field_name="dipole", energy_engine=short_range_2ednn_isotropic, parameters=config["short_range"], enable_jit=True)
bto.add_self_interaction('short_range_3', field_name="dipole", energy_engine=short_range_3rdnn_isotropic, parameters=config["short_range"], enable_jit=True)
bto.add_self_interaction('dipole_dipole', field_name="dipole", energy_engine=dipole_dipole_ewald, parameters=config["born"]|config["lattice"], enable_jit=False)

homo_config = config["elastic"].copy()
homo_config['N'] = L**3
bto.add_self_interaction('homo_elastic', field_name="gstrain", energy_engine=homo_elastic_energy, parameters=homo_config, enable_jit=True)
bto.add_mutual_interaction('homo_strain_dipole', field_name1="gstrain", field_name2="dipole", energy_engine=homo_strain_dipole_interaction, parameters=config["elastic_dipole"], enable_jit=True)

# bto.add_mutual_interaction('elastic', field_name1="lstrain", field_name2="gstrain", energy_engine=elastic_energy, parameters=config["elastic"], enable_jit=True)
# bto.add_mutual_interaction('inhomo_strain_dipole', field_name1="lstrain", field_name2="dipole", energy_engine=inhomo_strain_dipole_interaction, parameters=config["elastic_dipole"], enable_jit=True)

interaction_name = []
for interaction in bto._self_interaction_dict:
    interaction_name.append(interaction)
for interaction in bto._mutual_interaction_dict:
    interaction_name.append(interaction)


In [18]:

print('mass:', bto.get_field_by_name('dipole').get_mass().flatten())
bto.update_force()
print('max force before optimization',jnp.abs(bto.get_field_by_name("dipole").get_force()).max())
print('average field before optimization',bto.get_field_by_name("dipole").get_values().mean())
for interaction in interaction_name:
    print('E({})={}eV'.format( interaction, bto.calc_energy_by_name(interaction)))
print('total E:{}eV'.format(bto.calc_potential_energy()))
minimizer = MDMinimize(bto, max_iter=500, tol=1e-5, dt=0.01)
minimizer.minimize()

equilibrium_field = bto.get_field_by_name("dipole").get_values().copy()
print('max force after optimization',jnp.abs(bto.get_field_by_name("dipole").get_force()).max())
print('average field after optimization',bto.get_field_by_name("dipole").get_values().mean())
for interaction in interaction_name:
    print('E({})={}eV'.format( interaction, bto.calc_energy_by_name(interaction)))
print('total E:{}eV'.format(bto.calc_potential_energy()))

print('field:', equilibrium_field[:2,:2,:2])

mass: [40. 40. 40. ... 40. 40. 40.]
max force before optimization 0.3274665
average field before optimization 0.10000395
E(self_onsite)=372.35321044921875eV
E(short_range_1)=-72.6681900024414eV
E(short_range_2)=104.4072036743164eV
E(short_range_3)=74.23656463623047eV
E(dipole_dipole)=-480.2322692871094eV
E(homo_elastic)=0.0eV
E(homo_strain_dipole)=0.0eV
total E:-1.903472900390625eV
max force after optimization 0.051407196
average field after optimization 0.08763559
E(self_onsite)=270.4761657714844eV
E(short_range_1)=-55.832672119140625eV
E(short_range_2)=80.18939208984375eV
E(short_range_3)=57.01458740234375eV
E(dipole_dipole)=-369.4257507324219eV
E(homo_elastic)=11.236802101135254eV
E(homo_strain_dipole)=-22.454978942871094eV
total E:-28.79645538330078eV
field: [[[[0.08779135 0.0875623  0.08756227]
   [0.08779135 0.0875623  0.08756227]]

  [[0.08779135 0.0875623  0.08756227]
   [0.08779135 0.0875623  0.08756227]]]


 [[[0.08779135 0.0875623  0.08756227]
   [0.08779135 0.0875623  0.087

In [12]:
temp_list = [ 20,40,60,80,100,120,140]
# average_field = np.zeros(len(temp_list))
log_freq = 100
total_time = 10
dt = 0.001
relax_steps = int(10/dt)
total_steps = int(total_time / dt)
niters = total_steps // log_freq
field_history = []
for it, temperature in enumerate(temp_list):
    simulation = SimulationNVTLangevin(bto, dt=dt, temperature=temperature, gamma=1/(100*dt))
    # simulation.system.get_field_by_name('dipole').set_values(equilibrium_field.copy())
    simulation.init_velocity(mode='gaussian')
    simulation.step(relax_steps)
    print('T={}K'.format(temperature))
    average_field = []
    for ii in range(niters):
        simulation.step(log_freq)
        # print('velocity:', bto.get_field_by_name('dipole').get_velocity().flatten())
        # print('field:', bto.get_field_by_name('dipole').get_values().flatten())
        pot_E = bto.calc_potential_energy()
        kin_E = bto.calc_kinetic_energy()
        total_E = pot_E + kin_E
        # average_field[it] += bto.get_field_by_name('dipole').get_values().mean() / niters
        average_field.append(bto.get_field_by_name('dipole').get_values().mean())
        print('=================T={}K, iter={}======================='.format(temperature, ii))
        # print('pot energy:', pot_E)
        # print('kine energy:', kin_E)
        # print('total energy:', total_E)
        print('temperature:', bto.calc_temp_by_name('dipole'))
        print('average field:', average_field)
        # print('field:', bto.get_field_by_name('dipole').get_values().flatten())
    field_history.append(average_field)
field_history = jnp.array(field_history)


T=20K
=================T=20K, iter=0=======================
temperature: 20.20452212634687
average field: [Array(0.83408706, dtype=float64)]
=================T=20K, iter=1=======================
temperature: 21.00819530495236
average field: [Array(0.83408706, dtype=float64), Array(0.83407766, dtype=float64)]
=================T=20K, iter=2=======================
temperature: 19.488827029240653
average field: [Array(0.83408706, dtype=float64), Array(0.83407766, dtype=float64), Array(0.8340668, dtype=float64)]
=================T=20K, iter=3=======================
temperature: 19.987322096423295
average field: [Array(0.83408706, dtype=float64), Array(0.83407766, dtype=float64), Array(0.8340668, dtype=float64), Array(0.83407672, dtype=float64)]
=================T=20K, iter=4=======================
temperature: 19.889544986595507
average field: [Array(0.83408706, dtype=float64), Array(0.83407766, dtype=float64), Array(0.8340668, dtype=float64), Array(0.83407672, dtype=float64), Array(0.83408

KeyboardInterrupt: 